version: '2'

services:
  postgres:
    image: postgres
    networks:
      - app
    ports:
      - "3001:5432"
  node-server:
    image: node
    working_dir: /usr/src/app
    volumes:
      - $PWD:/usr/src/app
    command: "npm run server"
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - app
    restart: unless-stopped

networks:
  app:
