version: '2'

services:
  postgres:
    image: postgres
    networks:
      - app
    ports:
      - "3001:5432"
  node-server:
    image: node
    working_dir: /usr/src/app
    volumes:
      - $PWD:/usr/src/app
    command: "node server.js"
    ports:
      - "3000:3000"
    networks:
      - app

networks:
  app:
